function New_features = compute_features_of_ROI(...
                                    Input_Signal_ROI, ...
                                    signal_type, ...
                                    Start_Index, ...
                                    Fs)  
    New_features    = struct();
    
    % If the Signal Region of index is close to the begingin index of the
	% signal, we have to manipulate the code.
    calc_index      = @(x) x - find(Start_Index == Start_Index(1), 1, 'last' ) + Start_Index(1);
    
    switch signal_type
        case 'ECG'
            % Detect the peak of the ROI. 
            Max_Index                   = find(max(Input_Signal_ROI) == Input_Signal_ROI, 1, 'last' );
            Max_Index                   = calc_index(Max_Index);
            Max_Index                   = modify_index_location(...
                                                Max_Index, ...
                                                Start_Index);
            
            New_features(1).Max_Index   = Max_Index;
         
        case 'PPG'
    
            % Detect the peak of the ROI. 
            [~, Max_Index_Save]       	= max(Input_Signal_ROI);
            
            Max_Index_Save             	= find_local_minima_maxima(...
                                            Input_Signal_ROI, ...
                                            Max_Index_Save, ...
                                            0.1, ...
                                            Fs, ...
                                            'Max');
            
            Max_Index_Save              = min(Max_Index_Save);
            Max_Index                   = calc_index(Max_Index_Save);
            Max_Index                   = modify_index_location(...
                                                Max_Index, ...
                                                Start_Index);
            New_features(1).Max_Index   = Max_Index;
            
            % Detect the valley of the ROP
            Input_Signal_ROI_Minima     = Input_Signal_ROI(1:Max_Index_Save);
            [~, Min_Index]              = min(Input_Signal_ROI_Minima);
            
            Min_Index                   = find_local_minima_maxima(...
                                            Input_Signal_ROI_Minima, ...
                                            Min_Index, ...
                                            0.1, ...
                                            Fs, ...
                                            'Min');
                                        
            Min_Index                   = max(Min_Index);
            Min_Index                   = calc_index(Min_Index);
            Min_Index                   = modify_index_location(...
                                                Min_Index, ...
                                                Start_Index);
            New_features(1).Min_Index   = Min_Index;
            
        otherwise
    end
    
end