function Rem_features = remove_marker(...
                            Time, ...
                            Input_Signal, ...
                            signal_type, ...
                            New_features, ...
                            Rem_features, ...
                            Index_Detections_ROI, ...
                            detections)
                            
    switch signal_type
        case 'ECG'
            
                for i = 1:size(New_features, 1)
                    if ~isempty(Index_Detections_ROI)
                        Rem_features(i).Max_Index   = detections(Index_Detections_ROI);
                        plot(Time(Rem_features(i).Max_Index), ...
                            Input_Signal(Rem_features(i).Max_Index), ...
                                'ok', ...
                                'MarkerSize', 10, ...
                                'LineWidth', 5);
                    end                    
                end
                
        case 'PPG'
            
                for i = 1:size(New_features, 1)
                    
                    if ~isempty(Index_Detections_ROI)
                        Rem_features(i).Max_Index   = detections(Index_Detections_ROI, 1);
                        Rem_features(i).Min_Index   = detections(Index_Detections_ROI, 2);
                        plot(Time(Rem_features(i).Max_Index), ...
                            Input_Signal(Rem_features(i).Max_Index), ...
                                'ok', ...
                                'MarkerSize', 10, ...
                                'LineWidth', 5);
                        plot(Time(Rem_features(i).Min_Index), ...
                                Input_Signal(Rem_features(i).Min_Index), ...
                                    'ok', ...
                                    'MarkerSize', 10, ...
                                    'LineWidth', 5);
                    end
                    
                end
                
        otherwise
    end
end