% Author : Anand Chandrasekhar
% Here, we fit a exponential function to the into vector
% Fitting an exponential function : P(x) = P_inf + P0 * exp( - (x/Tau) )
% Range cannot be modified while fitting the function

% X                 : Time Vector
% Y                 : Pressure Waveform ( select the diastolic decay region of
%                       the pressure waveform
% P_inf_Range_LIM   : Example : [min(Y)-1, 0]
% Delta_P_inf       : Exmaple 10
% plot_data         : 1 if you want to plot data
% range_Tau         : Exmaple [0.1 0.6]
% delta_inc_P_in    : 0.1
function [Tau_sel, ...
            P_inf_sel, ...
            comments, ...
            start_ptr_min,...
            end_ptr_min, ...
            Num_iteration, ...
            Exp_Y, ...
            X_decay_Ex, ...
            Est_Y_Ex, ...
            BP_sel] ...
                    = find_exponetial_decay_from_waveform_without_Range_modification(...
                            X, ...
                            Y, ...
                            P_inf_Range_LIM, ... 
                            range_Tau,...
                            resolution_pressure)

    if length(X) ~= length(Y)
        comments = 'Length mismatch';
        fprintf('Length of X and Y should be same. Error\n')
        return;
    end
    
    if ~exist('resolution_pressure', 'var')
        resolution_pressure = 1;
    end
    
    if exist('P_inf_Range_LIM', 'var') && ~isempty(P_inf_Range_LIM)
        P_inf_range     = P_inf_Range_LIM(1):-resolution_pressure:P_inf_Range_LIM(2);
    end
    
    if isempty(P_inf_Range_LIM)
        P_inf_range     = Y(end)+resolution_pressure:-resolution_pressure:0;
        if isempty(P_inf_range)
            P_inf_range = 0;
        end
    end
    
    comments        = '';
    Num_iteration   = 1;
    start_ptr_min   = 1;
	end_ptr_min     = length(X);
    
   [P_inf_sel, ~, Tau_sel, Exp_Y, X_decay_Ex, Est_Y_Ex] ...
                    = find_exponential_decay_parameter(...
                            X, ...
                            Y, ...
                            P_inf_range, ...
                            range_Tau); 
    BP_sel = nanmean(Y);    
end