function [P_inf_sel, ...
                Tau_sel, ...
                Error_Message, ...
                X_decay_Ex, Est_Y_Ex, ...
                BP_sel] ...
                    = find_exponential_decay_parameter_X_segments(...
                            New_T_exp, New_P_exp, N_range)
                        
    Output = struct();
    Range_N = (N_range(1):N_range(2));
    for Idx = 1:length(Range_N)
        %fprintf('%2d \t', Range_N(Idx));
        [P_inf(Idx, 1), ...
            Output(Idx, 1).Tau_sel, ...
            Error_Message{Idx, 1}, ...
            ~, ...
            Output(Idx, 1).X, Output(Idx, 1).Y, ...
            Error(Idx, 1), ...
            Output(Idx, 1).BP_sel] ...
                    = find_exponential_decay_parameter_multiple_segments(...
                        New_T_exp, ...
                        New_P_exp, Range_N(Idx));
    end

    [~, I]          = min(Error);
    Tau_sel         = Output(I, 1).Tau_sel;
    P_inf_sel       = P_inf(I, 1);
    Error_Message   = Error_Message{I, 1};
    X_decay_Ex      = Output(I, 1).X;
    Est_Y_Ex        = Output(I, 1).Y;
    BP_sel          = Output(I, 1).BP_sel;   
end